version: '3'

services:
  express-app:
    image: rdip01/express-application-deployment:latest
    container_name: express-container
    restart: always
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - express-app
